/*
 * M3ScaleAccountManagement.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/17/2016
 */
using System;
using M3ScaleAccountManagement.PCL.Controllers;
using M3ScaleAccountManagement.PCL.Http.Client;

namespace M3ScaleAccountManagement.PCL
{
    public partial class M3ScaleAccountManagementClient
    {

        /// <summary>
        /// Singleton access to ApplicationPlan controller
        /// </summary>
        public ApplicationPlanController ApplicationPlan
        {
            get
            {
                return ApplicationPlanController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Account controller
        /// </summary>
        public AccountController Account
        {
            get
            {
                return AccountController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Signup controller
        /// </summary>
        public SignupController Signup
        {
            get
            {
                return SignupController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to AccountPlan controller
        /// </summary>
        public AccountPlanController AccountPlan
        {
            get
            {
                return AccountPlanController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to AccountFeature controller
        /// </summary>
        public AccountFeatureController AccountFeature
        {
            get
            {
                return AccountFeatureController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Proxy controller
        /// </summary>
        public ProxyController Proxy
        {
            get
            {
                return ProxyController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to User controller
        /// </summary>
        public UserController User
        {
            get
            {
                return UserController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Application controller
        /// </summary>
        public ApplicationController Application
        {
            get
            {
                return ApplicationController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Webhooks controller
        /// </summary>
        public WebhooksController Webhooks
        {
            get
            {
                return WebhooksController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to UserProviderAccount controller
        /// </summary>
        public UserProviderAccountController UserProviderAccount
        {
            get
            {
                return UserProviderAccountController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Service controller
        /// </summary>
        public ServiceController Service
        {
            get
            {
                return ServiceController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to MappingRule controller
        /// </summary>
        public MappingRuleController MappingRule
        {
            get
            {
                return MappingRuleController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to EndUser controller
        /// </summary>
        public EndUserController EndUser
        {
            get
            {
                return EndUserController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to EndUserPlan controller
        /// </summary>
        public EndUserPlanController EndUserPlan
        {
            get
            {
                return EndUserPlanController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ServicePlan controller
        /// </summary>
        public ServicePlanController ServicePlan
        {
            get
            {
                return ServicePlanController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ServicePlanFeature controller
        /// </summary>
        public ServicePlanFeatureController ServicePlanFeature
        {
            get
            {
                return ServicePlanFeatureController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ServiceFeature controller
        /// </summary>
        public ServiceFeatureController ServiceFeature
        {
            get
            {
                return ServiceFeatureController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Metric controller
        /// </summary>
        public MetricController Metric
        {
            get
            {
                return MetricController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to MetricMethod controller
        /// </summary>
        public MetricMethodController MetricMethod
        {
            get
            {
                return MetricMethodController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to EndUserPlanLimit controller
        /// </summary>
        public EndUserPlanLimitController EndUserPlanLimit
        {
            get
            {
                return EndUserPlanLimitController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ApplicationPlanPricingRules controller
        /// </summary>
        public ApplicationPlanPricingRulesController ApplicationPlanPricingRules
        {
            get
            {
                return ApplicationPlanPricingRulesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ApplicationPlanLimit controller
        /// </summary>
        public ApplicationPlanLimitController ApplicationPlanLimit
        {
            get
            {
                return ApplicationPlanLimitController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ApplicationPlanLimits controller
        /// </summary>
        public ApplicationPlanLimitsController ApplicationPlanLimits
        {
            get
            {
                return ApplicationPlanLimitsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ApplicationPlanFeature controller
        /// </summary>
        public ApplicationPlanFeatureController ApplicationPlanFeature
        {
            get
            {
                return ApplicationPlanFeatureController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ActiveDocs controller
        /// </summary>
        public ActiveDocsController ActiveDocs
        {
            get
            {
                return ActiveDocsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Nginx controller
        /// </summary>
        public NginxController Nginx
        {
            get
            {
                return NginxController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to AccountPlanFeature controller
        /// </summary>
        public AccountPlanFeatureController AccountPlanFeature
        {
            get
            {
                return AccountPlanFeatureController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public M3ScaleAccountManagementClient() { }
    }
}