/*
 * M3ScaleAccountManagement.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/17/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using M3ScaleAccountManagement.PCL;

namespace M3ScaleAccountManagement.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum RoleEnum
    {
        MEMBER, //TODO: Write general description for this method
        ADMIN, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type RoleEnum
    /// </summary>
    public static class RoleEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "member", "admin" };

        /// <summary>
        /// Converts a RoleEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The RoleEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(RoleEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case RoleEnum.MEMBER:
                case RoleEnum.ADMIN:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of RoleEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of RoleEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<RoleEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into RoleEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed RoleEnum value</returns>
        public static RoleEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type RoleEnum", value));

            return (RoleEnum) index;
        }
    }
} 