/*
 * M3ScaleAccountManagement.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/17/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using M3ScaleAccountManagement.PCL;

namespace M3ScaleAccountManagement.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum ScopeEnum
    {
        APPLICATIONPLAN, //TODO: Write general description for this method
        SERVICEPLAN, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type ScopeEnum
    /// </summary>
    public static class ScopeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "ApplicationPlan", "ServicePlan" };

        /// <summary>
        /// Converts a ScopeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The ScopeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(ScopeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case ScopeEnum.APPLICATIONPLAN:
                case ScopeEnum.SERVICEPLAN:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of ScopeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of ScopeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<ScopeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into ScopeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed ScopeEnum value</returns>
        public static ScopeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type ScopeEnum", value));

            return (ScopeEnum) index;
        }
    }
} 