/*
 * M3ScaleAccountManagement.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/17/2016
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using M3ScaleAccountManagement.PCL;
using M3ScaleAccountManagement.PCL.Http.Request;
using M3ScaleAccountManagement.PCL.Http.Response;
using M3ScaleAccountManagement.PCL.Http.Client;
using M3ScaleAccountManagement.PCL.Exceptions;
using M3ScaleAccountManagement.PCL.Models;

namespace M3ScaleAccountManagement.PCL.Controllers
{
    public partial class MetricMethodController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static MetricMethodController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static MetricMethodController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new MetricMethodController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// Deletes the method of a metric.
        /// </summary>
        /// <param name="accessToken">Required parameter: Example: </param>
        /// <param name="serviceId">Required parameter: Example: </param>
        /// <param name="metricId">Required parameter: Example: </param>
        /// <param name="id">Required parameter: Example: </param>
        /// <return>Returns the dynamic response from the API call</return>
        public dynamic DeleteAdminApiServicesMetricsMethodsIdXml(
                string accessToken,
                int serviceId,
                int metricId,
                int id)
        {
            Task<dynamic> t = DeleteAdminApiServicesMetricsMethodsIdXmlAsync(accessToken, serviceId, metricId, id);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Deletes the method of a metric.
        /// </summary>
        /// <param name="accessToken">Required parameter: Example: </param>
        /// <param name="serviceId">Required parameter: Example: </param>
        /// <param name="metricId">Required parameter: Example: </param>
        /// <param name="id">Required parameter: Example: </param>
        /// <return>Returns the dynamic response from the API call</return>
        public async Task<dynamic> DeleteAdminApiServicesMetricsMethodsIdXmlAsync(
                string accessToken,
                int serviceId,
                int metricId,
                int id)
        {
            //the base uri for api requestss
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/admin/api/services/{service_id}/metrics/{metric_id}/methods/{id}.xml");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "service_id", serviceId },
                { "metric_id", metricId },
                { "id", id }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "access_token", accessToken }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Delete(_queryUrl, _headers, null);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<dynamic>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Updates a method of a metric.
        /// </summary>
        /// <param name="accessToken">Required parameter: Example: </param>
        /// <param name="serviceId">Required parameter: Example: </param>
        /// <param name="metricId">Required parameter: Example: </param>
        /// <param name="id">Required parameter: Example: </param>
        /// <param name="friendlyName">Optional parameter: Example: </param>
        /// <param name="unit">Optional parameter: Example: </param>
        /// <return>Returns the dynamic response from the API call</return>
        public dynamic UpdateAdminApiServicesMetricsMethodsIdXml(
                string accessToken,
                int serviceId,
                int metricId,
                int id,
                string friendlyName = null,
                string unit = null)
        {
            Task<dynamic> t = UpdateAdminApiServicesMetricsMethodsIdXmlAsync(accessToken, serviceId, metricId, id, friendlyName, unit);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Updates a method of a metric.
        /// </summary>
        /// <param name="accessToken">Required parameter: Example: </param>
        /// <param name="serviceId">Required parameter: Example: </param>
        /// <param name="metricId">Required parameter: Example: </param>
        /// <param name="id">Required parameter: Example: </param>
        /// <param name="friendlyName">Optional parameter: Example: </param>
        /// <param name="unit">Optional parameter: Example: </param>
        /// <return>Returns the dynamic response from the API call</return>
        public async Task<dynamic> UpdateAdminApiServicesMetricsMethodsIdXmlAsync(
                string accessToken,
                int serviceId,
                int metricId,
                int id,
                string friendlyName = null,
                string unit = null)
        {
            //the base uri for api requestss
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/admin/api/services/{service_id}/metrics/{metric_id}/methods/{id}.xml");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "service_id", serviceId },
                { "metric_id", metricId },
                { "id", id }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "access_token", accessToken },
                { "friendly_name", friendlyName },
                { "unit", unit }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Put(_queryUrl, _headers, null);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<dynamic>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Returns the method of a metric.
        /// </summary>
        /// <param name="accessToken">Required parameter: Example: </param>
        /// <param name="serviceId">Required parameter: Example: </param>
        /// <param name="metricId">Required parameter: Example: </param>
        /// <param name="id">Required parameter: Example: </param>
        /// <return>Returns the dynamic response from the API call</return>
        public dynamic GetAdminApiServicesMetricsMethodsIdXml(
                string accessToken,
                int serviceId,
                int metricId,
                int id)
        {
            Task<dynamic> t = GetAdminApiServicesMetricsMethodsIdXmlAsync(accessToken, serviceId, metricId, id);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Returns the method of a metric.
        /// </summary>
        /// <param name="accessToken">Required parameter: Example: </param>
        /// <param name="serviceId">Required parameter: Example: </param>
        /// <param name="metricId">Required parameter: Example: </param>
        /// <param name="id">Required parameter: Example: </param>
        /// <return>Returns the dynamic response from the API call</return>
        public async Task<dynamic> GetAdminApiServicesMetricsMethodsIdXmlAsync(
                string accessToken,
                int serviceId,
                int metricId,
                int id)
        {
            //the base uri for api requestss
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/admin/api/services/{service_id}/metrics/{metric_id}/methods/{id}.xml");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "service_id", serviceId },
                { "metric_id", metricId },
                { "id", id }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "access_token", accessToken }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<dynamic>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Creates a method under a metric.
        /// </summary>
        /// <param name="accessToken">Required parameter: Example: </param>
        /// <param name="serviceId">Required parameter: Example: </param>
        /// <param name="metricId">Required parameter: Example: </param>
        /// <param name="friendlyName">Required parameter: Example: </param>
        /// <param name="unit">Required parameter: Example: </param>
        /// <param name="systemName">Optional parameter: Example: </param>
        /// <return>Returns the dynamic response from the API call</return>
        public dynamic CreateAdminApiServicesMetricsMethodsXml(
                string accessToken,
                int serviceId,
                int metricId,
                string friendlyName,
                string unit,
                string systemName = null)
        {
            Task<dynamic> t = CreateAdminApiServicesMetricsMethodsXmlAsync(accessToken, serviceId, metricId, friendlyName, unit, systemName);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Creates a method under a metric.
        /// </summary>
        /// <param name="accessToken">Required parameter: Example: </param>
        /// <param name="serviceId">Required parameter: Example: </param>
        /// <param name="metricId">Required parameter: Example: </param>
        /// <param name="friendlyName">Required parameter: Example: </param>
        /// <param name="unit">Required parameter: Example: </param>
        /// <param name="systemName">Optional parameter: Example: </param>
        /// <return>Returns the dynamic response from the API call</return>
        public async Task<dynamic> CreateAdminApiServicesMetricsMethodsXmlAsync(
                string accessToken,
                int serviceId,
                int metricId,
                string friendlyName,
                string unit,
                string systemName = null)
        {
            //the base uri for api requestss
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/admin/api/services/{service_id}/metrics/{metric_id}/methods.xml");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "service_id", serviceId },
                { "metric_id", metricId }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "access_token", accessToken },
                { "friendly_name", friendlyName },
                { "unit", unit },
                { "system_name", systemName }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, null);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<dynamic>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// List the methods of a metric. Methods are metrics that are children of a parent metric.
        /// </summary>
        /// <param name="accessToken">Required parameter: Example: </param>
        /// <param name="serviceId">Required parameter: Example: </param>
        /// <param name="metricId">Required parameter: Example: </param>
        /// <return>Returns the dynamic response from the API call</return>
        public dynamic GetAdminApiServicesMetricsMethodsXml(string accessToken, int serviceId, int metricId)
        {
            Task<dynamic> t = GetAdminApiServicesMetricsMethodsXmlAsync(accessToken, serviceId, metricId);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// List the methods of a metric. Methods are metrics that are children of a parent metric.
        /// </summary>
        /// <param name="accessToken">Required parameter: Example: </param>
        /// <param name="serviceId">Required parameter: Example: </param>
        /// <param name="metricId">Required parameter: Example: </param>
        /// <return>Returns the dynamic response from the API call</return>
        public async Task<dynamic> GetAdminApiServicesMetricsMethodsXmlAsync(string accessToken, int serviceId, int metricId)
        {
            //the base uri for api requestss
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/admin/api/services/{service_id}/metrics/{metric_id}/methods.xml");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "service_id", serviceId },
                { "metric_id", metricId }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "access_token", accessToken }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<dynamic>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

    }
} 